# Site
repository: jk-junhokim/jk-junhokim.github.io
# favicon: images/favicon.ico

# Personal info
name: 김준호
title: Computer Science 전공 @ Rice University
email: jk84@rice.edu
website: https://grinders.tistory.com/

# Dark Mode (true/false/never)
darkmode: never

# Social links
github_username:  jk-junhokim
# stackoverflow_username: "00000001"
instagram_username: junhok0715
linkedin_username: jk-junhokim
# orcid_username: 0000-0000-0000-0000

# Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpeg
about_content: | # this will include new lines to allow paragraphs
  안녕하세요.<br/><br/>
  라이스 대학교에 재학중인 2학년 컴퓨터 사이언스 전공 학생입니다.<br/><br/>
  컴퓨팅 사고, 알고리즘, 데이터 구조, 선형대수학, 객체지향 프로그래밍 등의 수업을 들으며 엔지니어로서의 길을 걸어가고 있는 중입니다.<br/><br/>
  군복학 이후 학교 수업 및 활동에 적극적으로 참여하고 배우며 현재로서 실무에 뛰어들고자 인턴십 기회를 구하고 있습니다.<br/><br/>
  군복무 간 Flask를 이용한 파이썬 기반 백엔드 구축을 해보며 본격적으로 개인 프로젝트 및 방향성을 찾기 시작했습니다. 지금은 머신러닝에 몰두하고 있으며, **numpy**와 **pandas**에 점차 익숙해지며 **신경망** 탐구를 하고 있습니다. 파이썬 기반으로 **CNN**을 구축해보았으며 현재는 **PyTorch**와 **RNN**을 공부하고 있습니다.<br/><br/>
  2023년도 여름을 활용하여 **Computer Vision & Deep Learning**에 올인하려고 합니다. 인턴십을 통해 저의 성장뿐만 아니라 기업의 발전도 함께 이루어내고 싶습니다. 다양한 사람과 함께 일하며 날카로운 피드백을 통해 서로의 성장을 돕는 환경에 기여하도록 하겠습니다.<br/><br/>
  <mark>기술 & 언어 스택:<mark/><br/>
  - 상: Python, Java, IntelliJ, VsCode <br/>
  - 중: Flask, Pandas, PyTorch, Git, Github, Jupyter Notebook <br/>


# Education Section
# educaton_title: Education

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag